-- MySQL Script generated by MySQL Workbench
-- Fri Apr 19 23:54:37 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema App
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema App
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `solucio8_mobil` DEFAULT CHARACTER SET utf8 ;
USE `solucio8_mobil` ;

-- -----------------------------------------------------
-- Table `solucio8_mobil`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solucio8_mobil`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `unidad_de_medida` VARCHAR(45) NULL,
  `Cantidad_presentacion` VARCHAR(45) NULL,
  `principio_activo` VARCHAR(45) NULL,
  `CUM` VARCHAR(45) NULL,
  `nombre_comercial` VARCHAR(45) NULL,
  `nombre_laboratorio` VARCHAR(45) NULL,
  `unidades_disponibles` VARCHAR(45) NULL,
  `farmacia` VARCHAR(45) NULL,
  PRIMARY KEY (`idproducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solucio8_mobil`.`Direccionamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solucio8_mobil`.`Direccionamiento` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `IDDireccionamiento` INT NULL,
  `NoPrescripcion` VARCHAR(45) NULL,
  `Tecnologia` VARCHAR(45) NULL,
  `Consecutivo` VARCHAR(45) NULL,
  `Direccionamientocol` VARCHAR(45) NULL,
  `Paciente` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  `FecMaxEnt` VARCHAR(45) NULL,
  `NoEntrega` VARCHAR(45) NULL,
  `NoSubEntrega` VARCHAR(45) NULL,
  `CodMunEnt` VARCHAR(45) NULL,
  `CantTotAEntregar` VARCHAR(45) NULL,
  `DirPaciente` VARCHAR(45) NULL,
  `CodSerTecAEntregar` INT(10) NOT NULL,
  `CodEPS` VARCHAR(45) NOT NULL,
  `FecDireccionamiento` VARCHAR(45) NULL,
  `idproducto` INT NOT NULL,
  PRIMARY KEY (`ID`, `idproducto`),
  INDEX `producto_idx` (`idproducto` ASC),
  CONSTRAINT `producto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `solucio8_mobil`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solucio8_mobil`.`transacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solucio8_mobil`.`transacciones` (
  `idtransaccione` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  `fecha` VARCHAR(45) NULL,
  `farmacia` VARCHAR(45) NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idtransaccione`),
  INDEX `fk_transacciones_producto1_idx` (`producto_idproducto` ASC),
  CONSTRAINT `fk_transacciones_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `solucio8_mobil`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;