INSERT INTO `producto` VALUES (1, 'PAQUETE', '60', 'PANAL', '50', 'PANAL DESECHABLE', 'TENA', '50', 'CALLE50');
INSERT INTO `producto` VALUES (2, 'TABLETA', '60', 'NAPROXENO', '45', 'NAPROXENO TABLETA', 'LASANTE', '550', 'CALLE125');
INSERT INTO `producto` VALUES (3, 'PAQUETE', '60', 'PANITO', '1000', 'PANITOS HUMEDOS', 'PROCAPS', '10', 'CALLE134');
